version: "3"
services:
  hub:
    image: selenium/hub:3.14
  chrome:
    image: selenium/node-chrome:3.14
    shm_size: '2gb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.14
    shm_size: '1gb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  bdd-tst:
    image: asmorales/cucumber-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - browser=chrome
      - env=remote
      - CUCUMBER_OPTIONS=classpath:Features
    volumes:
     - ./target/test-output:/target/target/test-output